nodeLinker: node-modules
packageExtensions:
  '@astrojs/language-server@*':
    dependencies:
      typescript: ^6
  '@astrojs/compiler-binding-wasm32-wasi@^0.4':
    dependencies:
      '@emnapi/core': ^1.11.1
      '@emnapi/runtime': ^1.11.1
  recma-jsx@^1:
    dependencies:
      acorn: ^8
  '@astrojs/mdx@^7.0':
    dependencies:
      satteri: ^0.9
