nodeLinker: pnp
packageExtensions:
  '@oxc-parser/binding-wasm32-wasi@^0.120.0':
    dependencies:
      '@emnapi/core': ^1.11.1
      '@emnapi/runtime': ^1.11.1
  '@tanstack/devtools@^0.14.2':
    dependencies:
      csstype: ^3.2.3
  '@tanstack/devtools-ui@^0.7.1':
    dependencies:
      csstype: ^3.2.3
  '@tanstack/react-router-devtools@^1.167.2':
    dependencies:
      csstype: ^3.2.3
  '@tanstack/start-plugin-core@^1.167.2':
    dependencies:
      vite: ^8
